name: 'Configure Kubectl with StrongDM'
description: 'Setup kubectl config using StrongDM CLI'
author: 'software.com'
branding:
  icon: settings
  color: blue
inputs:
  sdm-admin-token:
    description: 'Token for SDM service account'
    required: true
  sdm-download-url:
    description: 'Custom SDM CLI download URL. If not provided the default will be used'
    required: false
    default: https://app.strongdm.com/releases/cli/linux
  sdm-stdout-logs:
    description: 'If true, logs go to STDOUT rather than sdm.log'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download StrongDM
      run: curl -J -L -o sdm.zip ${{ inputs.sdm-download-url }}
      shell: bash
    - name: Unzip StrongDM
      run: unzip sdm.zip
      shell: bash
    - name: Install StrongDM
      run: sudo ./sdm install --admin-token=${{ inputs.sdm-admin-token }}
      shell: bash
    - name: Login to StrongDM and listen for local connections
      run: SDM_DOCKERIZED=${{ inputs.sdm-stdout-logs }} sdm login --admin-token=${{ inputs.sdm-admin-token }} && sdm listen & 
      shell: bash
    - name: Update StrongDM config
      run: sdm k8s update-config
      shell: bash
