name: 'Configure Kubectl with StrongDM'
description: 'Setup kubectl config using StrongDM CLI'
author: 'software.com'
branding:
  icon: settings
  color: blue
inputs:
  sdm-admin-token:
    description: 'Token for SDM service account'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download StrongDM
      run: curl -J -L -o sdm.zip https://app.strongdm.com/releases/cli/linux
      shell: bash
    - name: Unzip StrongDM
      run: unzip sdm.zip
      shell: bash
    - name: Install StrongDM
      run: sudo ./sdm install --admin-token=${{ inputs.sdm-admin-token }}
      shell: bash
    - name: Login to StrongDM
      run: sdm login --admin-token=${{ inputs.sdm-admin-token }}
      shell: bash
    - name: Update StrongDM config
      run: sdm k8s update-config
      shell: bash
