name: 'Configure Kubectl with StrongDM'
description: 'Setup kubectl config using StrongDM CLI'
author: 'software.com'
branding:
  icon: settings
  color: blue
inputs:
  sdm-admin-token:
    description: 'Token for SDM service account'
    required: true
  sdm-download-url:
    description: 'Custom SDM CLI download URL. If not provided the default will be used'
    required: false
    default: https://app.strongdm.com/releases/cli/linux
runs:
  using: 'composite'
  steps:
    - name: Download StrongDM
      run: curl -J -L -o sdm.zip ${{ inputs.sdm-download-url }}
      shell: bash
    - name: Unzip StrongDM
      run: unzip sdm.zip
      shell: bash
    - name: Install StrongDM
      run: sudo ./sdm install --nologin
      shell: bash
    - name: Login to StrongDM
      run: sdm login --admin-token=${{ inputs.sdm-admin-token }}
      shell: bash
    - name: Wait for StrongDM to start
      run: |
        until sdm status &> /dev/null;
        do
          sleep 1
          echo "waiting for SDM to start"
        done
      shell: bash
    - name: Update StrongDM config
      run: sdm k8s update-config
      shell: bash
